// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NVSP.Data;

#nullable disable

namespace NVSP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NVSP.Models.BanGiamKhao", b =>
                {
                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<string>("MaGv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_gv");

                    b.HasKey("IdHd", "MaGv");

                    b.HasIndex("MaGv");

                    b.ToTable("ban_giam_khao");
                });

            modelBuilder.Entity("NVSP.Models.BanToChuc", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_giang_vien");

                    b.Property<DateTime>("BatDauNk")
                        .HasColumnType("datetime2")
                        .HasColumnName("bat_dau_nk");

                    b.Property<DateTime>("KetThucNk")
                        .HasColumnType("datetime2")
                        .HasColumnName("ket_thuc_nk");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaGiangVien");

                    b.ToTable("ban_to_chuc");
                });

            modelBuilder.Entity("NVSP.Models.BcnKhoa", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_giang_vien");

                    b.Property<DateTime>("BatDauNk")
                        .HasColumnType("datetime2")
                        .HasColumnName("bat_dau_nk");

                    b.Property<DateTime>("KetThucNk")
                        .HasColumnType("datetime2")
                        .HasColumnName("ket_thuc_nk");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("khoa");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaGiangVien");

                    b.ToTable("bcn_khoa");
                });

            modelBuilder.Entity("NVSP.Models.CanBoLop", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sinh_vien");

                    b.Property<DateTime>("BatDauNk")
                        .HasColumnType("datetime2")
                        .HasColumnName("bat_dau_nk");

                    b.Property<DateTime>("KetThucNk")
                        .HasColumnType("datetime2")
                        .HasColumnName("ket_thuc_nk");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaSinhVien");

                    b.ToTable("can_bo_lop");
                });

            modelBuilder.Entity("NVSP.Models.ChamDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DangKyCaNhanId")
                        .HasColumnType("int");

                    b.Property<int?>("DangKyNhomIdNhom")
                        .HasColumnType("int");

                    b.Property<decimal>("Diem")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("diem");

                    b.Property<int>("IdDangKy")
                        .HasColumnType("int")
                        .HasColumnName("id_dang_ky");

                    b.Property<int>("IdHdThi")
                        .HasColumnType("int")
                        .HasColumnName("id_hd_thi");

                    b.Property<string>("LoaiBaiThi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_bai_thi");

                    b.Property<string>("MaBgk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_bgk");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.HasKey("Id");

                    b.HasIndex("DangKyCaNhanId");

                    b.HasIndex("DangKyNhomIdNhom");

                    b.HasIndex("IdHdThi");

                    b.ToTable("cham_diem");
                });

            modelBuilder.Entity("NVSP.Models.ChiTietRubric", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("TieuChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tieu_chi");

                    b.Property<int>("DiemToiDa")
                        .HasColumnType("int")
                        .HasColumnName("diem_toi_da");

                    b.HasKey("Id", "TieuChi");

                    b.ToTable("chi_tiet_rubric");
                });

            modelBuilder.Entity("NVSP.Models.DangKyCaNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<string>("MaSv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sv");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("IdHd");

                    b.HasIndex("MaSv");

                    b.ToTable("dang_ky_ca_nhan");
                });

            modelBuilder.Entity("NVSP.Models.DangKyNhom", b =>
                {
                    b.Property<int>("IdNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_nhom");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhom"));

                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<int>("MaThamGia")
                        .HasColumnType("int")
                        .HasColumnName("ma_tham_gia");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_nhom");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdNhom");

                    b.HasIndex("IdHd");

                    b.HasIndex("MaThamGia")
                        .IsUnique();

                    b.ToTable("dang_ky_nhom");
                });

            modelBuilder.Entity("NVSP.Models.DangKyThamDu", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sv");

                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaSv", "IdHd");

                    b.HasIndex("IdHd");

                    b.ToTable("dang_ky_tham_du");
                });

            modelBuilder.Entity("NVSP.Models.DiemDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AnhMinhChung")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("anh_minh_chung");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.ToTable("diem_danh");
                });

            modelBuilder.Entity("NVSP.Models.DiemRenLuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Diem")
                        .HasColumnType("int")
                        .HasColumnName("diem");

                    b.Property<string>("KyHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ky_hoc");

                    b.Property<string>("MaSv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sv");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nam_hoc");

                    b.Property<string>("XepLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("xep_loai");

                    b.HasKey("Id");

                    b.HasIndex("MaSv");

                    b.ToTable("diem_ren_luyen");
                });

            modelBuilder.Entity("NVSP.Models.DsRubrics", b =>
                {
                    b.Property<int>("IdRubric")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rubric");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRubric"));

                    b.Property<string>("TenRubric")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_rubric");

                    b.HasKey("IdRubric");

                    b.ToTable("ds_rubrics");
                });

            modelBuilder.Entity("NVSP.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_giang_vien");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("khoa");

                    b.HasKey("MaGiangVien");

                    b.ToTable("giang_vien");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongHoTro", b =>
                {
                    b.Property<int>("IdHdHoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_hd_ho_tro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHdHoTro"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dia_diem");

                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<string>("LoaiHoTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_ho_tro");

                    b.Property<string>("MaGv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_gv");

                    b.Property<string>("TenHd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_hd");

                    b.Property<DateTime>("TgBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("tg_bat_dau");

                    b.Property<DateTime>("TgKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("tg_ket_thuc");

                    b.HasKey("IdHdHoTro");

                    b.HasIndex("IdHd");

                    b.HasIndex("MaGv");

                    b.ToTable("hoat_dong_ho_tro");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongThamDu", b =>
                {
                    b.Property<int>("IdHdThamDu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_hd_tham_du");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHdThamDu"));

                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<string>("TenHd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_hd");

                    b.HasKey("IdHdThamDu");

                    b.HasIndex("IdHd");

                    b.ToTable("hoat_dong_tham_du");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongThi", b =>
                {
                    b.Property<int>("IdHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHd"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dia_diem");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hinh_thuc");

                    b.Property<int>("IdRubric")
                        .HasColumnType("int")
                        .HasColumnName("id_rubric");

                    b.Property<int>("IdSk")
                        .HasColumnType("int")
                        .HasColumnName("id_sk");

                    b.Property<string>("TenHd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_hd");

                    b.Property<DateTime>("TgBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("tg_bat_dau");

                    b.Property<DateTime>("TgKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("tg_ket_thuc");

                    b.HasKey("IdHd");

                    b.HasIndex("IdRubric");

                    b.HasIndex("IdSk");

                    b.HasIndex("TenHd", "IdSk")
                        .IsUnique();

                    b.ToTable("hoat_dong_thi");
                });

            modelBuilder.Entity("NVSP.Models.KetQua", b =>
                {
                    b.Property<int>("IdChamDiem")
                        .HasColumnType("int")
                        .HasColumnName("id_cham_diem");

                    b.Property<string>("GiaiThuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("giai_thuong");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdChamDiem");

                    b.ToTable("ket_qua");
                });

            modelBuilder.Entity("NVSP.Models.LogGCN", b =>
                {
                    b.Property<int>("IdGcn")
                        .HasColumnType("int")
                        .HasColumnName("id_gcn");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hanh_dong");

                    b.Property<int>("MaBtc")
                        .HasColumnType("int")
                        .HasColumnName("ma_btc");

                    b.HasKey("IdGcn");

                    b.ToTable("log_gcn");
                });

            modelBuilder.Entity("NVSP.Models.LogTraCuu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGcn")
                        .HasColumnType("int")
                        .HasColumnName("id_gcn");

                    b.Property<DateTime>("TgTraCuu")
                        .HasColumnType("datetime2")
                        .HasColumnName("tg_tra_cuu");

                    b.HasKey("Id");

                    b.HasIndex("IdGcn");

                    b.ToTable("log_tra_cuu");
                });

            modelBuilder.Entity("NVSP.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sinh_vien");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("khoa");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("lop");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nganh");

                    b.Property<string>("NienKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nien_khoa");

                    b.HasKey("MaSinhVien");

                    b.ToTable("sinh_vien");
                });

            modelBuilder.Entity("NVSP.Models.SuKien", b =>
                {
                    b.Property<int>("IdSk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSk"));

                    b.Property<string>("MaBtc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_btc");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int")
                        .HasColumnName("nam_hoc");

                    b.Property<string>("TenSk")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_sk");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdSk");

                    b.HasIndex("MaBtc");

                    b.HasIndex("TenSk", "NamHoc")
                        .IsUnique();

                    b.ToTable("su_kien");
                });

            modelBuilder.Entity("NVSP.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("LoaiTk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_tk");

                    b.Property<string>("MaCaNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_ca_nhan");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.HasKey("Id");

                    b.HasIndex("MaCaNhan")
                        .IsUnique();

                    b.ToTable("tai_khoan");
                });

            modelBuilder.Entity("NVSP.Models.ThanhVienNhom", b =>
                {
                    b.Property<int>("IdNhom")
                        .HasColumnType("int")
                        .HasColumnName("id_nhom");

                    b.Property<string>("MaSv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_sv");

                    b.HasKey("IdNhom", "MaSv");

                    b.HasIndex("MaSv");

                    b.ToTable("thanh_vien_nhom");
                });

            modelBuilder.Entity("NVSP.Models.ThongTinGCN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("doi_tuong");

                    b.Property<string>("GiaiThuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("giai_thuong");

                    b.Property<int>("IdHd")
                        .HasColumnType("int")
                        .HasColumnName("id_hd");

                    b.Property<int?>("KetQuaIdChamDiem")
                        .HasColumnType("int");

                    b.Property<string>("LoaiChungNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_chung_nhan");

                    b.Property<int>("MaBtc")
                        .HasColumnType("int")
                        .HasColumnName("ma_btc");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("IdHd");

                    b.HasIndex("KetQuaIdChamDiem");

                    b.ToTable("thong_tin_gcn");
                });

            modelBuilder.Entity("NVSP.Models.BanGiamKhao", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("BanGiamKhaos")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.GiangVien", "GiangVien")
                        .WithMany("BanGiamKhaos")
                        .HasForeignKey("MaGv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HoatDongThi");
                });

            modelBuilder.Entity("NVSP.Models.BanToChuc", b =>
                {
                    b.HasOne("NVSP.Models.GiangVien", "GiangVien")
                        .WithMany("BanToChucs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("NVSP.Models.BcnKhoa", b =>
                {
                    b.HasOne("NVSP.Models.GiangVien", "GiangVien")
                        .WithMany("BcnKhoas")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("NVSP.Models.CanBoLop", b =>
                {
                    b.HasOne("NVSP.Models.SinhVien", "SinhVien")
                        .WithMany("CanBoLops")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("NVSP.Models.ChamDiem", b =>
                {
                    b.HasOne("NVSP.Models.DangKyCaNhan", null)
                        .WithMany("ChamDiems")
                        .HasForeignKey("DangKyCaNhanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NVSP.Models.DangKyNhom", null)
                        .WithMany("ChamDiems")
                        .HasForeignKey("DangKyNhomIdNhom")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("ChamDiems")
                        .HasForeignKey("IdHdThi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoatDongThi");
                });

            modelBuilder.Entity("NVSP.Models.ChiTietRubric", b =>
                {
                    b.HasOne("NVSP.Models.DsRubrics", "DsRubrics")
                        .WithMany("ChiTietRubrics")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DsRubrics");
                });

            modelBuilder.Entity("NVSP.Models.DangKyCaNhan", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("DangKyCaNhans")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyCaNhans")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoatDongThi");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("NVSP.Models.DangKyNhom", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("DangKyNhoms")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoatDongThi");
                });

            modelBuilder.Entity("NVSP.Models.DangKyThamDu", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThamDu", "HoatDongThamDu")
                        .WithMany("DangKyThamDus")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyThamDus")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoatDongThamDu");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("NVSP.Models.DiemRenLuyen", b =>
                {
                    b.HasOne("NVSP.Models.SinhVien", "SinhVien")
                        .WithMany("DiemRenLuyens")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("NVSP.Models.GiangVien", b =>
                {
                    b.HasOne("NVSP.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiangVien")
                        .HasForeignKey("NVSP.Models.GiangVien", "MaGiangVien")
                        .HasPrincipalKey("NVSP.Models.TaiKhoan", "MaCaNhan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongHoTro", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("HoatDongHoTros")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.GiangVien", "GiangVien")
                        .WithMany("HoatDongHoTros")
                        .HasForeignKey("MaGv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HoatDongThi");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongThamDu", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("HoatDongThamDus")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoatDongThi");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongThi", b =>
                {
                    b.HasOne("NVSP.Models.DsRubrics", "DsRubrics")
                        .WithMany("HoatDongThis")
                        .HasForeignKey("IdRubric")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.SuKien", "SuKien")
                        .WithMany("HoatDongThis")
                        .HasForeignKey("IdSk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DsRubrics");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("NVSP.Models.KetQua", b =>
                {
                    b.HasOne("NVSP.Models.ChamDiem", "ChamDiem")
                        .WithOne("KetQua")
                        .HasForeignKey("NVSP.Models.KetQua", "IdChamDiem")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChamDiem");
                });

            modelBuilder.Entity("NVSP.Models.LogGCN", b =>
                {
                    b.HasOne("NVSP.Models.ThongTinGCN", "ThongTinGCN")
                        .WithMany("LogGCNs")
                        .HasForeignKey("IdGcn")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ThongTinGCN");
                });

            modelBuilder.Entity("NVSP.Models.LogTraCuu", b =>
                {
                    b.HasOne("NVSP.Models.ThongTinGCN", "ThongTinGCN")
                        .WithMany("LogTraCuus")
                        .HasForeignKey("IdGcn")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ThongTinGCN");
                });

            modelBuilder.Entity("NVSP.Models.SinhVien", b =>
                {
                    b.HasOne("NVSP.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("SinhVien")
                        .HasForeignKey("NVSP.Models.SinhVien", "MaSinhVien")
                        .HasPrincipalKey("NVSP.Models.TaiKhoan", "MaCaNhan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("NVSP.Models.SuKien", b =>
                {
                    b.HasOne("NVSP.Models.BanToChuc", "BanToChuc")
                        .WithMany("SuKiens")
                        .HasForeignKey("MaBtc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BanToChuc");
                });

            modelBuilder.Entity("NVSP.Models.ThanhVienNhom", b =>
                {
                    b.HasOne("NVSP.Models.DangKyNhom", "DangKyNhom")
                        .WithMany("ThanhVienNhoms")
                        .HasForeignKey("IdNhom")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.SinhVien", "SinhVien")
                        .WithMany("ThanhVienNhoms")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DangKyNhom");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("NVSP.Models.ThongTinGCN", b =>
                {
                    b.HasOne("NVSP.Models.HoatDongThi", "HoatDongThi")
                        .WithMany("ThongTinGCNs")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NVSP.Models.KetQua", null)
                        .WithMany("ThongTinGCNs")
                        .HasForeignKey("KetQuaIdChamDiem")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HoatDongThi");
                });

            modelBuilder.Entity("NVSP.Models.BanToChuc", b =>
                {
                    b.Navigation("SuKiens");
                });

            modelBuilder.Entity("NVSP.Models.ChamDiem", b =>
                {
                    b.Navigation("KetQua")
                        .IsRequired();
                });

            modelBuilder.Entity("NVSP.Models.DangKyCaNhan", b =>
                {
                    b.Navigation("ChamDiems");
                });

            modelBuilder.Entity("NVSP.Models.DangKyNhom", b =>
                {
                    b.Navigation("ChamDiems");

                    b.Navigation("ThanhVienNhoms");
                });

            modelBuilder.Entity("NVSP.Models.DsRubrics", b =>
                {
                    b.Navigation("ChiTietRubrics");

                    b.Navigation("HoatDongThis");
                });

            modelBuilder.Entity("NVSP.Models.GiangVien", b =>
                {
                    b.Navigation("BanGiamKhaos");

                    b.Navigation("BanToChucs");

                    b.Navigation("BcnKhoas");

                    b.Navigation("HoatDongHoTros");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongThamDu", b =>
                {
                    b.Navigation("DangKyThamDus");
                });

            modelBuilder.Entity("NVSP.Models.HoatDongThi", b =>
                {
                    b.Navigation("BanGiamKhaos");

                    b.Navigation("ChamDiems");

                    b.Navigation("DangKyCaNhans");

                    b.Navigation("DangKyNhoms");

                    b.Navigation("HoatDongHoTros");

                    b.Navigation("HoatDongThamDus");

                    b.Navigation("ThongTinGCNs");
                });

            modelBuilder.Entity("NVSP.Models.KetQua", b =>
                {
                    b.Navigation("ThongTinGCNs");
                });

            modelBuilder.Entity("NVSP.Models.SinhVien", b =>
                {
                    b.Navigation("CanBoLops");

                    b.Navigation("DangKyCaNhans");

                    b.Navigation("DangKyThamDus");

                    b.Navigation("DiemRenLuyens");

                    b.Navigation("ThanhVienNhoms");
                });

            modelBuilder.Entity("NVSP.Models.SuKien", b =>
                {
                    b.Navigation("HoatDongThis");
                });

            modelBuilder.Entity("NVSP.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiangVien")
                        .IsRequired();

                    b.Navigation("SinhVien")
                        .IsRequired();
                });

            modelBuilder.Entity("NVSP.Models.ThongTinGCN", b =>
                {
                    b.Navigation("LogGCNs");

                    b.Navigation("LogTraCuus");
                });
#pragma warning restore 612, 618
        }
    }
}
